### ISSUE TITLE
without modal

### ISSUE THREAD

**Issue by luisrudge** [JedWatson/react-date-select#7]
Is there a way to use this without the date picker being inside a modal?

**Comment by jossmac** [comment]
This is a requirement, yes.

**Comment by dcousens** [comment]
@jossmac please re-clarify.  It is possible to use this without the date picker being inside a modal.   I think you meant that this is going to be on the roadmap?

**Comment by jossmac** [comment]
> This is a requirement, yes.

What I meant by that is being able to render the react-date-select component inline, or "outside a modal" is on the roadmap and is a requirement for the component to be useful.
