### ISSUE TITLE
cant customize button classes

### ISSUE THREAD

**Issue by luisrudge** [JedWatson/react-date-select#9]

**Comment by jossmac** [comment]
Hi @luisrudge,

The buttons use very specific classes so they _don't_ conflict with any existing button styles.

Perhaps the buttons should use predefined variables that can be easily updated?

**Comment by luisrudge** [comment]
maybe it should receive via props

**Comment by jossmac** [comment]
I just can't see it being helpful, remembering of course that the buttons have two different states when in a single calendar VS multi-picker.

Could you explain a use case for this?

**Comment by luisrudge** [comment]
the use case is when you're using bootstrap, for example and you want to add a specific set of classes

**Comment by jossmac** [comment]
If you take a look at the single date picker and the multi date picker side-by-side you'll notice that the footer buttons are **very** different

Applying bootstrap classes, for instance `btn btn-primary`, would only work for the multi picker - making the single picker footer buttons break.

I think a more prudent solution would be to write a small bit of CSS, leveraging LESS's ability to use classes as mixins:
```
.multi-picker .DateSelectFooter__button--primary {
  .btn();
  .btn-primary();
}
```

**Comment by luisrudge** [comment]
I'm talking about [this button](https://github.com/JedWatson/react-date-select/blob/b82c0ab3db783fb6721a412fa2f89fa744b6fe9e/src/DateSelect.js#L58). Not the buttons inside the picker itself

**Comment by jossmac** [comment]
Oh right!

The trigger element will be completely arbitrary with the updates @dcousens is making in the `refacto` branch.

Sorry for the confusion, closing

##### Important
When you're creating issues in the future please use specific issue names, and write a detailed description.
